### ISSUE TITLE
暗色菜单栏下图标与背景融为一体

### ISSUE THREAD

**Issue by xernyuii** [langyanduan/Reborn#1]
RT.

- macOS 10.12.6 (16G29)
- 系统偏好设置中选中 暗色菜单栏和Dock
> 最左边是与背景融为一体Reborn图标, 无法正常显示 ![17247d45-1925-426b-b86e-960ec99000ea](https://user-images.githubusercontent.com/17217233/35765897-c406e216-0908-11e8-96cd-923c84e0eb1d.png)
> 点击后可以看见选项![a0c8eb3a-b144-4cf9-940d-0bf2f9d61c8e](https://user-images.githubusercontent.com/17217233/35765903-eea065f6-0908-11e8-8e51-f7819585771d.png)
> 看了好久才发现是这个问题....

**Comment by langyanduan** [comment]
fixed. [0.3.4 build 316](https://github.com/langyanduan/Reborn/releases/tag/0.3.4)
