### ISSUE TITLE
openvpn和reborn 同时使用，openvpn失效

### ISSUE THREAD

**Issue by zinbers** [langyanduan/Reborn#11]
openvpn的客户端用的是shimo

openvpn的连接不受reborn的开闭影响。
但是reborn开启的话，访问特定ip失效，关闭reborn,访问正常
在reborn配置route里面添加直连特定ip，无效

**Comment by langyanduan** [comment]
猜测是 shimo 修改了路由表  接管了原先应该走 reborn 的流量，你可以通过 `netstat -nr` 命令看下

reborn 也算是一款vpn工具，不建议和其他vpn工具同时使用
