### ISSUE TITLE
开了RebornCN及HK不走代理 ，其他走代理的情况下https://www.dropbox.com无法打开

### ISSUE THREAD

**Issue by lucky0l** [langyanduan/Reborn#12]
开了RebornCN及HK不走代理 ，其他走代理的情况下https://www.dropbox.com无法打开

Mac OSX 10.14 Beta (18A293u)
Safari 版本 12.0 (14606.1.17.40.4)

页面提示
<img width="620" alt="image" src="https://user-images.githubusercontent.com/14807931/41137303-0c264b0c-6b0d-11e8-8924-9f35d969d9db.png">

Chrome 打开提示

无法访问此网站
网址为 https://www.dropbox.com/ 的网页可能暂时无法连接，或者它已永久性地移动到了新网址。
ERR_TUNNEL_CONNECTION_FAILED

**Comment by langyanduan** [comment]
reborn 的版本是多少

感觉可能跟 dns 解析有关，分别用两个配置看下dns解析的结果，用这个命令 `dig www.dropbox.com`

**Comment by lucky0l** [comment]
Reborn的版本是0.4.52（396）
两个配置分别dig后得到的地址不一样……奇怪的，在配置里面只是SS的代理不同，其他的是一样，两个SS一个是台湾的线路，一个是美国的线路，如下，第一个是台湾的线路dig出来的结果，第二个是美国线路dig出来的结果，打不开的线路就是台湾的。
; <<>> DiG 9.10.6 <<>> www.dropbox.com
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 24414
;; flags: qr rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 0

;; QUESTION SECTION:
;www.dropbox.com.		IN	A

;; ANSWER SECTION:
www.dropbox.com.	32	IN	A	162.125.82.1

;; Query time: 130 msec
;; SERVER: 240.0.200.200#53(240.0.200.200)
;; WHEN: Sun Jun 10 15:08:30 CST 2018
;; MSG SIZE  rcvd: 49
------------------------------------------------------------

; <<>> DiG 9.10.6 <<>> www.dropbox.com
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 62050
;; flags: qr rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 0

;; QUESTION SECTION:
;www.dropbox.com.		IN	A

;; ANSWER SECTION:
www.dropbox.com.	32	IN	A	162.125.7.1

;; Query time: 133 msec
;; SERVER: 240.0.200.200#53(240.0.200.200)
;; WHEN: Sun Jun 10 15:09:06 CST 2018
;; MSG SIZE  rcvd: 49

**Comment by langyanduan** [comment]
Reborn内置的ip地址数据库是 MaxMind GEOLite2，162.125.82.1 识别出来是香港的ip，所以走了HK的直连规则，162.125.7.1识别是美国，会走代理规则

**Comment by lucky0l** [comment]
那为什么不同的代理线路出来的IP不一样呢？而且我在把HK和CN都去掉了，也就是意味着所有的连接都走代理呀，为什么仍然访问不了呢？因为解析出来的地址的问题？

**Comment by langyanduan** [comment]
不同代理出来的IP不一样很正常，可能上来cdn等等原因。
至于为什么把 HK 和 CN 都去掉了还是不能访问，这个比较奇怪，最好能把日志文件丢上来我看下。
