### ISSUE TITLE
Features: monitoring all network requests

### ISSUE THREAD

**Issue by unpin** [langyanduan/Reborn#13]
可否增加一个观察或记录所有网络请求的方法，类似 Surge Dashboard ，或者打 Log 的方式。
这样可以方便查看网络是否正确的分发到代理还是直连。
比如添加一个选项，开启时将所有的网络请求输出到 Log 文件。

**Comment by langyanduan** [comment]
从 0.5.3 版本开始支持查看网络信息了，具体见 README
