### ISSUE TITLE
Checking updates not working

### ISSUE THREAD

**Issue by jarnanchen** [langyanduan/Reborn#18]
On v0.5.41, checking for updates not receiving latest release

**Comment by langyanduan** [comment]
Check for updates to get json from https://github.com/langyanduan/Reborn/blob/master/api/VERSION2

> checking for updates not receiving latest release

This means that the request times out or you receive the message `You’re up-to-date!`?

**Comment by jarnanchen** [comment]
OK, Can't reproduce now.
Should be my net problem.
