### ISSUE TITLE
局域网流量没有被统计

### ISSUE THREAD

**Issue by LomotHo** [langyanduan/Reborn#23]
在使用time machine备份或者samba服务时，局域网流量没有被统计

**Comment by langyanduan** [comment]
路由表里都会有一条规则，指明局域网网段直接走网关，就不会经过reborn转发了。

**Comment by langyanduan** [comment]
简单点说，局域网流量不会经过reborn，也不会被统计到流量

**Comment by LomotHo** [comment]
你的意思是局域网流量不走utun6网卡对吗

**Comment by langyanduan** [comment]
是的，你可以用 netstat -nr 看到局域网出口在 en* 上
