### ISSUE TITLE
FINAL, PROXY 不起作用

### ISSUE THREAD

**Issue by bebound** [langyanduan/Reborn#24]
版本是最新的build574

RULES最后的FINAL, PROXY不起作用 似乎被当作FINAL，DIRECT处理
在dashboard中看到未匹配的网址都被当作DIRECT(FINAL)处理了

RULES内容大约为

[RULES]
DOMAIN,gs-loc.apple.com,DIRECT
DOMAIN,mvod.itunes.apple.com,DIRECT
DOMAIN,streamingaudio.itunes.apple.com,DIRECT
DOMAIN-SUFFIX,cdn-apple.com,DIRECT
DOMAIN-SUFFIX,lcdn-locator.apple.com,DIRECT
DOMAIN-SUFFIX,lcdn-registration.apple.com,DIRECT
DOMAIN-SUFFIX,ls.apple.com,DIRECT
PROCESS,storedownloadd,DIRECT
DOMAIN-SUFFIX,lookup-api.apple.com,PROXY
DOMAIN-SUFFIX,me.com,PROXY
DOMAIN-SUFFIX,cn,DIRECT
DOMAIN,ip.bjango.com,DIRECT
DOMAIN-SUFFIX,blizzard.com,DIRECT
DOMAIN-SUFFIX,battle.net,DIRECT
DOMAIN-SUFFIX,google.com,PROXY
DOMAIN-SUFFIX,googleapis.com,PROXY
DOMAIN-SUFFIX,gstatic.com,PROXY
DOMAIN-SUFFIX,gmail.com,PROXY
GEOIP,CN,DIRECT
FINAL,PROXY

**Comment by langyanduan** [comment]
能发一下具体配置吗。不方便的话可以发到我邮箱 **langyanduan@gmail.com**，注意删掉服务器的信息

**Comment by langyanduan** [comment]
配置里的 sspai.com 规则冲突引发里一个bug，请更新到最新版本 0.5.50 来修复这个问题
