### ISSUE TITLE
reborn性能问题

### ISSUE THREAD

**Issue by bebound** [langyanduan/Reborn#29]
走代理情况下 6M/s下载速度
io.atoi.osx.reborn.helper 大约占用40% CPU
Reborn 占用20%
ss加密方式为chacha20-ietf-poly1305 CPU为I7-4870HQ
这个CPU使用率有点多吧 不知道有没有改进计划

另外在不走代理 使用proxyee-down开启64分段下载的情况下 CPU使用率也很高

**Comment by langyanduan** [comment]
设置中把统计网络信息选项关掉会好很多，然后 io.atoi.osx.reborn.helper 应该不会吃 cpu 的啊

**Comment by bebound** [comment]
这是下载速度为4M时的CPU使用率截图 （在istats menu下Reborn Core被当作atoi helper了）
已关闭统计网络信息
<img width="613" alt="screen shot 2018-08-26 at 15 24 22" src="https://user-images.githubusercontent.com/2227874/44625825-71633f00-a944-11e8-8279-f61f1b25c3ec.png">

**Comment by langyanduan** [comment]
你这个应该还没有关闭统计功能，关闭后要重新stop然后start一下，关于性能的问题后期优化吧，最近没啥空

**Comment by langyanduan** [comment]
更新到 v0.5.60 试一下， Reborn 应该不会吃 CPU 了
