### ISSUE TITLE
有计划支持规则从文件中读取吗？

### ISSUE THREAD

**Issue by lizhaode** [langyanduan/Reborn#32]
说一下我的需求，我会有走proxy的url和ip的列表，也有去广告（REJECT）的url和ip列表，这些列表加起来比较大

所以我一般是分成四个这样的文件

domainProxy.txt
domainReject.txt
ipProxy.txt
ipReject.txt

如果我现在还想用之前的配置文件的话，需要把他们都拷贝到同一个 xxxx.conf文件里

这样就会让我的conf文件太大了，所以想问问有没有计划支持 [RULES]的配置指定文件

**Comment by langyanduan** [comment]
v0.5.60 开始支持从文件读取规则组，具体见 [详情](../blob/master/v2/DETAIL.md) 和 [模板文件](../blob/master/v2/template-with-file-rule.conf)
