### ISSUE TITLE
如何搭配配置文件（https://github.com/langyanduan/Reborn/raw/master/v2/template.conf）使用呢？

### ISSUE THREAD

**Issue by luckypoem** [langyanduan/Reborn#35]
wget https://github.com/langyanduan/Reborn/releases/download/0.5.53/Reborn.zip
unzip Reborn.zip
(释放出Reborn.app目录）
open Reborn.app
(在mac的屏幕顶部出现了reborn的图标）
但是如何搭配配置文件（https://github.com/langyanduan/Reborn/raw/master/v2/template.conf）使用呢？没有可执行文件啊。

**Comment by langyanduan** [comment]
菜单栏点击 Profiles -> Open in Finder，把配置文件放进去

**Comment by luckypoem** [comment]
profiles目录在哪里

**Comment by luckypoem** [comment]
哦，知道了：
~/Library/Application Support/Reborn/Profiles

**Comment by luckypoem** [comment]
不过设置了浏览器的socks5代理服务器为127.0.0.1:1080,但是翻墙失败，为什么？

**Comment by langyanduan** [comment]
开了 reborn 之后就自动接管整个系统的流量了，不需要在浏览器上设置代理了

**Comment by langyanduan** [comment]
状态栏图标点开 Dashboard 看下规则是否匹配正确了，你的服务器用 IP 还是域名连接到，dig 一下看看具体的 IP 有几个
