### ISSUE TITLE
似乎会丢包?

### ISSUE THREAD

**Issue by ahlixinjie** [langyanduan/Reborn#4]
我很喜欢这款软件, 但是似乎还有些没有完善的地方
有次我开着这款软件, 用conda安装东西, conda安装失败了,  告诉我应有的字节长度和实际下载得到的字节长度不一致, 然后我用proxychains通过ss-ng代理才下载成功, 也就是说用这款软件下载的东西会不对? 

那次下载是这款软件有udp转发功能之前,  后来这款软件有udp转发功能了, 我以为应该没啥事了, 可是就在刚才我开着这款软件下载spotify, spotify一直告诉我下载失败(下到中间一半),  我还是开着ss-ng下好的..    所以我觉得这款软件可能会丢包之类的么?

**Comment by langyanduan** [comment]
能具体点吗，操作系统版本之类点。conda 版本，下载操作如命令还是 GUI 之类点。

**Comment by ahlixinjie** [comment]
ProductName:	Mac OS X
ProductVersion:	10.13.3
BuildVersion:	17D47

conda: conda 4.4.4, 用的命令行, conda install -c conda-forge jupyter_contrib_nbextensions
那次conda下载失败, 提示我软件应有多少字节, 实际下载得到多少字节, 不匹配, 所以不能安装.

spotify: 下载spotify installer安装Spotify, Spotify installer  总是下到一半就告诉我   install failed, try again in xxS,  试了好几次都没成功

上述两个操作我刚才又重新做了一遍, 没有复现我说的问题, 但是总感觉有时候会出现很奇怪的问题, 很像丢包了一样, 但是用SS-NG好像就很可靠从来没出现过问题. 所以可能在这也没办法给你提供更多有用的信息了

很喜欢这个软件, 希望能越来越好~~

**Comment by langyanduan** [comment]
这种情况一般是连接被断开了，至于具体原因不好排查，也可能不是 `reborn` 的原因，如果出现频率高的话反馈下路径，我在定位一下。

**Comment by langyanduan** [comment]
你可以先把日志发我邮箱 `langyanduan@gmail.com`，我先看看，日志在 `~/Library/Application Support/Reborn/XLogs`
