### ISSUE TITLE
请教作者，虚拟网卡的实现，相对于目前 Linux 上  iptables + ss -redir 各有什么优劣么？

### ISSUE THREAD

**Issue by programscape** [langyanduan/Reborn#5]
试用了下您的作品，从体验上来说，类似另一款代理工具 https://github.com/netheril96/MEOW/tree/master  ，都无需太多干预，对用户透明，非常方便。

还有一个问题，在服务器或者路由层无GUI环境下，我常常使用 iptables ，发现难点更多的在于分流上，如何正确及时、及时的区分国内外IP是个很棘手的事情，meow 的做法是白名单制，判定为国外，一律走代理，但有的国外网站在国内访问，由于CDN 或者专线之类，国内访问速度很不错。如果使用pac的黑名单制，某些不被墙的网站访问又的确很慢，很难折中， 您是怎么处理这件事情的呢？

**Comment by langyanduan** [comment]
`reborn` 内置了 smartdns 用来处理 ip 地址解析的问题，单纯的使用 iptables 可能会被 DNS 污染干扰，如果 dns 解析足够精准的话，两者应该不会有太大差别。
