### ISSUE TITLE
访问网站出现[Reborn] http parser - failure

### ISSUE THREAD

**Issue by lucky0l** [langyanduan/Reborn#7]
作者您好，访问http://club.huawei.com或者http://cn.club.vmall.com/thread-14232096-1-6.html都出现[Reborn] http parser - failure的提示.

系统版本：MAC OS 10.13.4 Beta (17E160e)
浏览器：Safari  11.1 (13605.1.27.2.1)
每次都出现，停掉Reborn后则可以打开。

配置文件就是copy的模版的，只是加了HK直接访问以及SS服务地址。

**Comment by langyanduan** [comment]
感谢反馈

这两个站点服务器返回的 http header 不标准，header field 中出现了非法字符，在 **0.4.33** 中做了兼容处理

**Comment by lucky0l** [comment]
谢谢，更新版本后好了，然而发现了另一个问题，之前没注意，在此版本的mac os下，重新启动后Reborn不能自动启动，不知道是否个例？

**Comment by langyanduan** [comment]
自动启动还没实现。。。有空会加上
